defaults: &defaults
  app:
    base_path: <%= Dir.pwd %>
    use_capistrano: false
    files_to_generate:
      my_config:
        extension: '.yml'
  my_first_value: 1
  my_second_value: 2
  my_fifth_value: 5
  nested_values: &nested_defaults
    my_third_value: 3
    my_fourth_value: 4
    my_sixth_value: 6

test:
  <<: *defaults
  my_first_value: 11
  nested_values:
    <<: *nested_defaults
    my_third_value: 13

development:
  <<: *defaults
  my_first_value: 11
  nested_values:
    <<: *nested_defaults
    my_third_value: 13
